# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
GOTOOLCHAIN: auto
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - JAVASCRIPT_ES
  - GO_GOLANGCI_LINT
  - HTML_DJLINT
  - CSS_STYLELINT
FLAVOR_SUGGESTIONS: false

HTML_DJLINT_ARGUMENTS: ["--profile", "golang", "-i", "H031,H006"] # Ignore H031: "Consider adding meta keywords", Ignore H006: "img tag should have height and width attributes"
HTML_DJLINT_FILE_EXTENSIONS: [".tmpl"]

CSS_STYLELINT_PRE_COMMANDS: 
  - command: npm install stylelint-selector-bem-pattern
  - command: npm install stylelint-config-standard-scss@14
