---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-go
    tag: 1.24.9-bookworm-node-20

inputs:
  - name: dis-design-system-go

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dis-design-system-go/ci/scripts/build.sh
